import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-pink-400 bg-size-100 text-white flex">
          Halo
          <div className="flex gap-x-4 justify-center w-full">
            <Link href="./">Home</Link>
            <Link href="./products">Product</Link>
            <Link href="./contact">Contact</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
