import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-pink-400 h-15 text-white flex px-4 items-center justify-between">
          <Image
            src="/icon.png"
            alt="Logo"
            width={50}
            height={50}
          />
          <Link href="./" className="font-bold">HappyMart</Link>
          <div className="flex gap-x-10 justify-center w-full font-bold">
            <Link href="./">Home</Link>
            <Link href="./products">Product</Link>
            <Link href="./contact">Contact</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
